[package]
name = "zklink_types"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
ethers = "2.0.2"
hex = "0.4"
num = { version = "0.4.0", features = ["serde"] }

# Crypto stuff
parity-crypto = { version = "0.9.0", features = ["publickey"] }
rand = "0.8"

serde = "1.0.137"
serde_json = "1.0.0"
thiserror = "1.0"

validator = { version = "0.15", features = ["derive"] }
zklink_crypto = { path = "../crypto" }
zklink_sdk_utils = { path = "../utils" }
uniffi = { version = "0.23", optional = true }
uniffi_macros = { version = "0.23", optional = true }

[dev-dependencies]
primitive-types = "0.12.1"
ethers = "2.0.2"

[build-dependencies]
uniffi_build = {version = "0.23", features=["builtin-bindgen"] }

[features]
default = ["ffi"]
ffi = ["uniffi", "uniffi_macros"]
