[package]
name = "zklink_interface"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee = { version = "0.15.1", features = ["server", "client", "macros"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
zklink_signers = { path = "../signer" }
zklink_sdk_types = { path = "../types" }

[features]
default = ["sync"]
sync = []
ffi = []
