[package]
name = "zklink_sdk_utils"
version = "2.0.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
num = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
