[package]
name = "bindings_sdk"
version = "0.1.0"
edition = "2021"

[lib]
name = "zklink_sdk"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
zklink_crypto = { path = "../../crypto", features = ["ffi"] }
