[package]
name = "zklink_sdk_wasm"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
zklink_signers = { path = "../../signer" }
wasm-bindgen = { version = "0.2.87",features = ["serde-serialize"] }
getrandom = { version = "0.2.10", features = ["js"] }
serde-wasm-bindgen = "0.5"
wasm-bindgen-futures = "0.4"
js-sys = "0.3.64"
hex = "0.4"
[features]
default = []
ffi = []

[dev-dependencies]
actix-rt = "2.7"
actix-web = "4.2"
futures = "0.3"
tokio = { version = "1", features = ["full"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
