[package]
name = "zklink_sdk_wasm"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
zklink_sdk_signers = { path = "../../signer" }
zklink_sdk_types = { path = "../../types" }
wasm-bindgen = { version = "0.2.87",features = ["serde-serialize"] }
getrandom = { version = "0.2.10", features = ["js"] }
[features]
default = []
ffi = []

[dev-dependencies]
actix-rt = "2.7"
actix-web = "4.2"
futures = "0.3"
tokio = { version = "1", features = ["full"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
